### ISSUE TITLE
jic

### ISSUE THREAD

**Issue by arial-alisha** [MattSkinner30/simple-chat-app#15]
```css
.notifications li .notification.info {
  background: #73dcb2;
}

.notifications li .notification.connect {
  background: #73dcb2;
}

.notification-container .notifications {
  list-style: none;
  display: flex;
  flex-direction: column-reverse;
  align-items: center;
  justify-content: flex-start;
  padding: 0;
  margin: 0;
}

.notifications li {
  height: 4rem;
  margin: 2rem 0;
}

.notifications li .notification {
  color: white;
  font-family: sans-serif;
}

.notification-container {
    position: fixed;
    bottom: 0;
    right: 0;
    height: 100vh;
    width: 10vw;
    min-width: 250px;
}

```
